version: '3.3'
services:
    cakephp:
        build:
            context: https://github.com/Corolario/CakePHP.git
            dockerfile: CakePHP-Dockerfile
        ports:
            - 8080:80
    mariadb:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: senharoot
            MYSQL_DATABASE: cakephp
            MYSQL_USER: usuariocake
            MYSQL_PASSWORD: senhacake
